[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1"
rust-version = "1.70"
edition = "2021"
license = "Apache-2.0"
authors = ["OpenQASM3 parser team"]
readme = "README.md"
keywords = ["QASM", "openqasm3", "parser"]
categories = ["parser-implementations"]
repository = "https://github.com/Qiskit/openqasm3_parser"

[workspace.dependencies]
# local crates
oq3_lexer = { path = "crates/oq3_lexer", version = "0.0.1" }
oq3_parser = { path = "crates/oq3_parser", version = "0.0.1" }
oq3_syntax = { path = "crates/oq3_syntax", version = "0.0.1" }
oq3_semantics = { path = "crates/oq3_semantics", version = "0.0.1" }
oq3_sourcegen = { path = "crates/oq3_sourcegen", version = "0.0.1" }
oq3_source_file = { path = "crates/oq3_source_file", version = "0.0.1" }

# non-local crates
limit = { version = "0.0.188", package = "ra_ap_limit" }
stdx = { version = "0.0.188", package = "ra_ap_stdx"}
triomphe = { version = "0.1.8", default-features = false, features = ["std"] }
smallvec = { version = "1.10.0", features = [
  "const_new",
  "union",
  "const_generics",
] }
smol_str = "0.2.0"
nohash-hasher = "0.2.0"
text-size = "1.1.0"
# can't upgrade due to dashmap depending on 0.12.3 currently
hashbrown = { version = "0.12.3", features = ["inline-more"], default-features = false }
