[toolchain]
# Keep in sync with Cargo.toml's `rust-version`.

# Copyright contributors to the openqasm-parser project

# FIXME: Our min required version is > than 1.64.0

channel = "1.70.0"
components = [
  "cargo",
  "clippy",
  "rust-std",
  "rustc",
  "rustfmt",
]
