[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
lexer.workspace = true
drop_bomb = "0.1.5"
limit = { version = "0.0.188", package = "ra_ap_limit" }

[dev-dependencies]
expect-test = "1.4.0"
