[package]
name = "lexer"
version = "0.0.0"
edition = "2021"

[dependencies]
unicode-xid = "0.2.0"

[dependencies.unicode-properties]
version = "0.1.0"
default-features = false
features = ["emoji"]

[dev-dependencies]
expect-test = "1.4.0"
